### ISSUE TITLE
Operationalize Deployment of Re:Dash

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#251]
In order to make Re:Dash more robust we need to automate deployment and backup at production scale. This includes things like:
- [ ] Dedicated PostGreSQL database
- [ ] Formula for Re:Dash deployment, configuration, and upgrades
- [ ] Dedicated Redis service (hosted or self-managed)
