### ISSUE TITLE
Ficus: Restore Legacy Dashboard features

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#311]
This is a mini-epic to restore the legacy dashboard features. The issues themselves are all stored on the mitocw/edx-platform repostiory:

- [ ] mitocw/edx-platform#74 Export Grades to Remote Gradebook (in progress)
- [ ] mitocw/edx-platform#75 Grade Downloads 
- [ ] mitocw/edx-platform#76 Pull enrollment data from remote gradebook
