### ISSUE TITLE
performance issues with 6.0001 quiz

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#457]
6.0001 gives in-class, on-platform quizzes. Approximately 450-500 students bring their own laptops to the lecture hall, log in to MITx and submit one or two problems to the grader. 

Students get some immediate feedback, so they know that the code runs and passes basic tests. Later, course staff re-process the submitted code for final grades and more detailed feedback.

We have seen two classes of user issues with these exams:

- Initial load of the course can take over a minute
- a significant portion of students never get a return from the grader. On the web page, they see a perpetual "processing" message and spinner.

We have identified a number of things we can do to mitigate these issues:

- [x] add more application instances of edx-platform
- [x] Use `/etc/hosts` to override the name xqueue uses to post grades back to edx-platform, to reduce network latency 
- [x] ~~mitodl/edx-platform#42 Make the post back URL for xqueue grades independently configurable, so we reduce network latency~~
- [x] Enable a shared cache across edx-platform instances. 
- [x] Turn off sticky sessions
- [x] Increase timeouts in xqueue-watcher
- [x] Improve logging in xqueue-watcher
- [x] Set callback_url in XQUEUE_INTERFACE to use edx-platform (see https://github.com/mitodl/edx-platform/issues/42#issuecomment-338704179)
  - [x] remove `/etc/hosts` changes 

Any changes that can be merged upstream to edX should be, and are included in this epic.

**Comment by pdpinch** [comment]
Looks like we've done all we can for now.
