### ISSUE TITLE
Ginkgo: MITx Spring 2018 QA bugs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#477]
This is an epic for tracking issues with the Spring 2018 release of MITx using Open edX's Ginkgo release. 

Significant issues:

- [x] Stellar integration (remote grade book) needs to be merged
- [x] Discussions aren't working
- [x] MITx theme (significant issues: #469, #475, #471)
- [x] ~~webhooks / gitreload isn't working~~
- [x] #476 "export to git with every course publish event" is not functioning 
- [x] #462 python_lib.zip imported through git doesn't work

Issues are also being tracked in https://github.mit.edu/mitx/Spring-2018/issues which can't be added to this epic.

**Comment by pdpinch** [comment]
I'm closing this epic, since we are on Hawthorn now.
