### ISSUE TITLE
Adding guard rails for Salt environments

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#864]
In order to reduce the occurrence of accidental configuration mismatches we need to implement strict separations between different environments and applications. To make this work effectively without introducing a significant cognitive burden we are going to use a set of approaches.

- [ ] Create an additional salt master that is exclusively for communicating with production infrastructure
- [ ] Implement Salt environments to separate code to separate branches for pre-prod and prod deployments
- [ ] Add node group specifications for more easily defining a set of targets

**Comment by shaidar** [comment]
While working on salt auto-scaling, I came across salt's [external authentication system](https://docs.saltstack.com/en/latest/topics/eauth/index.html#acl-eauth) and I was wondering whether we can leverage that (either to replace having multiple environments or as additional guard rails). The thinking would be that a separate account with privileges on production instances would have the rights to run specific salt commands.
